name: game_app
description: A new Flutter project.
publish_to: 'none' # 
version: 1.0.0+1
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cached_network_image: null
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_lints: ^1.0.0
  firebase_core: null
  firebase_analytics: ^9.1.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: null
  flutter_staggered_grid_view: ^0.4.0
  get: null
  get_storage: null
  http: null
  image_picker: ^0.8.4+4
  lottie: ^1.2.1
  permission_handler: ^8.3.0
  share: null
  step_progress_indicator: ^1.0.1
  url_launcher: ^6.1.5
  flutter_html: ^2.2.1
  restart_app: ^1.1.0
  flick_video_player: null
  vibration: ^1.7.5
  mime: ^1.0.1
  pull_to_refresh: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lang/
    - assets/lottie/

  fonts:
    - family: JosefinSansBold
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
    - family: JosefinSansSemiBold
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
    - family: JosefinSansMedium
      fonts:
        - asset: assets/fonts/JosefinSans-Medium.ttf
    - family: JosefinSansRegular
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
