name: game_app
version: 1.0.3+7
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: 
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  flutter_iconly: ^1.0.2
  firebase_messaging: ^14.3.0
  firebase_core: 
  firebase_core_platform_interface: ^4.5.3
  flutter_local_notifications: any
  get_storage: any
  http: any
  image_picker: ^0.8.4+4
  lottie: ^1.2.1
  permission_handler: ^11.0.1
  share: any
  url_launcher: ^6.1.5
  restart_app: ^1.1.0
  flutter_html: ^3.0.0-alpha.6
  vibration: ^1.7.5
  mime: ^1.0.1
  pull_to_refresh: 
  flick_video_player: any
  get: ^4.6.5
  file: ^6.1.4
  intl: ^0.18.0
  time_machine: ^0.9.17
  provider: ^6.0.5
  dio: ^5.3.0
  flutter_launcher_icons: ^0.11.0
  timer_count_down: 
  webview_flutter: ^4.0.0
 

  flutter:
    sdk: flutter
  async: ^2.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/image/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/image/logo.png"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  adaptive_icon_background: "assets/image/logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/image/logo.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lang/
    - assets/lottie/
    - assets/image/
  fonts:
    - family: JosefinSansBold
      fonts:
        - asset: assets/fonts/NormsProBold.otf
    - family: JosefinSansSemiBold
      fonts:
        - asset: assets/fonts/NormsProMedium.otf
    - family: JosefinSansMedium
      fonts:
        - asset: assets/fonts/NormsProRegular.otf
    - family: JosefinSansRegular
      fonts:
        - asset: assets/fonts/NormsProLight.otf
  uses-material-design: true
  generate: true
