name: game_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cached_network_image: any
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  flutter_iconly: ^1.0.2
  firebase_messaging: ^11.2.6
  firebase_core: any
  flutter_local_notifications: any
  # flutter_staggered_grid_view: ^0.4.0 
  get_storage: any
  http: any
  image_picker: ^0.8.4+4
  lottie: ^1.2.1 
  permission_handler: ^8.3.0
  share: any
  url_launcher: ^6.1.5
  restart_app: ^1.1.0
  flutter_html: ^2.2.1
  vibration: ^1.7.5
  mime: ^1.0.1
  pull_to_refresh: ^2.0.0
  video_compress: ^3.1.1
  flick_video_player: any
  get: 4.6.5
  file: ^6.1.4 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/icons/
    - assets/lang/
    - assets/lottie/
    - assets/image/
  fonts: 
    - family: JosefinSansBold
      fonts: 
        - asset: assets/fonts/NormsProBold.otf
    - family: JosefinSansSemiBold
      fonts: 
        - asset: assets/fonts/NormsProMedium.otf
    - family: JosefinSansMedium
      fonts: 
        - asset: assets/fonts/NormsProRegular.otf
    - family: JosefinSansRegular
      fonts: 
        - asset: assets/fonts/NormsProLight.otf
  uses-material-design: true
  generate: true

